"""Structured Study failures; documents remain untrusted data."""
from enum import Enum


class StudyErrorCode(str, Enum):
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    READ_FAILURE = "READ_FAILURE"
    FINGERPRINT_FAILURE = "FINGERPRINT_FAILURE"
    PARSE_FAILURE = "PARSE_FAILURE"
    ENCRYPTED_PDF = "ENCRYPTED_PDF"
    NO_USABLE_TEXT = "NO_USABLE_TEXT"
    REGISTRY_FAILURE = "REGISTRY_FAILURE"
    ENCODING_FAILURE = "ENCODING_FAILURE"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    INCOMPATIBLE_CHECKPOINT = "INCOMPATIBLE_CHECKPOINT"
    MEDIA_CORRUPT="MEDIA_CORRUPT"
    MEDIA_TOO_LARGE="MEDIA_TOO_LARGE"
    DURATION_LIMIT_EXCEEDED="DURATION_LIMIT_EXCEEDED"
    PAGE_LIMIT_EXCEEDED="PAGE_LIMIT_EXCEEDED"
    PIXEL_LIMIT_EXCEEDED="PIXEL_LIMIT_EXCEEDED"
    SEGMENT_LIMIT_EXCEEDED="SEGMENT_LIMIT_EXCEEDED"
    PROVIDER_TIMEOUT="PROVIDER_TIMEOUT"


class StudyError(Exception):
    def __init__(self, code: StudyErrorCode, message: str):
        self.code = code
        super().__init__(message)
