from enum import Enum
class PerceptionErrorCode(str,Enum):
    UNSUPPORTED_MEDIA="UNSUPPORTED_MEDIA";MEDIA_CORRUPT="MEDIA_CORRUPT";MEDIA_TOO_LARGE="MEDIA_TOO_LARGE";DURATION_LIMIT_EXCEEDED="DURATION_LIMIT_EXCEEDED";PAGE_LIMIT_EXCEEDED="PAGE_LIMIT_EXCEEDED";PIXEL_LIMIT_EXCEEDED="PIXEL_LIMIT_EXCEEDED";PERCEIVER_UNAVAILABLE="PERCEIVER_UNAVAILABLE";PROVIDER_FAILURE="PROVIDER_FAILURE";PROVIDER_TIMEOUT="PROVIDER_TIMEOUT";EXTRACTION_FAILED="EXTRACTION_FAILED";ARTIFACT_GENERATION_FAILED="ARTIFACT_GENERATION_FAILED";INVALID_LOCATOR="INVALID_LOCATOR";SEGMENT_LIMIT_EXCEEDED="SEGMENT_LIMIT_EXCEEDED";PERCEPTION_RUN_INCOMPATIBLE="PERCEPTION_RUN_INCOMPATIBLE";SCHEMA_MISMATCH="SCHEMA_MISMATCH"
class PerceptionError(Exception):
    def __init__(self,code:PerceptionErrorCode,message:str):self.code=code;super().__init__(message)
