from enum import Enum
class CouncilErrorCode(str,Enum):
    INVALID_COUNCIL_REQUEST="INVALID_COUNCIL_REQUEST";TOO_FEW_MEMBERS="TOO_FEW_MEMBERS";TOO_MANY_MEMBERS="TOO_MANY_MEMBERS";DUPLICATE_MEMBER="DUPLICATE_MEMBER";INVALID_MEMBER_PROFILE="INVALID_MEMBER_PROFILE";MEMBER_PROFILE_INCOMPATIBLE="MEMBER_PROFILE_INCOMPATIBLE";SHARED_STATE_MISMATCH="SHARED_STATE_MISMATCH";COUNCIL_BUDGET_EXCEEDED="COUNCIL_BUDGET_EXCEEDED";MEMBER_EXECUTION_FAILED="MEMBER_EXECUTION_FAILED";ANALYSIS_FAILED="ANALYSIS_FAILED";SYNTHESIS_FAILED="SYNTHESIS_FAILED"
class CouncilError(Exception):
    def __init__(self,code:CouncilErrorCode,message:str):self.code=code;super().__init__(message)
